framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'

        envelope:
            sender: 'admin@white-umbrella.fr'

        headers:
            From: 'White Rabbit"s Blog <admin@white-umbrella.fr>'
